cpi-bo/Controllers/ResponsibleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.UI;
using cpi_bo.Services;
using cpi_bo.Models;

namespace cpi_bo.Controllers
{
    public class ResponsibleController : AbstractSeguridadController
    {
        private TypeTableService typeTableService = new TypeTableService();
        private ResponsibleService responsibleService = new ResponsibleService();

        // GET: Responsable
        public ActionResult Index()
        {
            return View(responsibleService.GetResponsables());
        }

        public ActionResult AddResponsible()
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            return View();
        }
        [HttpPost]
        public ActionResult AddResponsible(ResponsibleModel respView)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");

            if (ModelState.IsValid)
            {
                if (responsibleService.AddResponsable(respView))
                {
                    TempData["Msg"] = alertHtml_ok(respView.RESPONSABLE_APELLIDO.ToUpper(), " responsable add Successfully");
                    return Redirect("/Responsible/Index");
                }
                else
                    TempData["Msg"] = alertHtml_error(respView.RESPONSABLE_APELLIDO.ToUpper(), "responsable add error");             
            }
            return View(respView);
        }

        public ActionResult EditResponsible(Int32 iRespId)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            return View(responsibleService.GetResponsables().Find(smodel => smodel.RESPONSABLE_ID == iRespId));
        }
        [HttpPost]
        public ActionResult EditResponsible(ResponsibleModel respView)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            if (ModelState.IsValid)
            {
                if (responsibleService.UpdateResponsable(respView))
                {
                    TempData["Msg"] = alertHtml_ok(respView.RESPONSABLE_APELLIDO, " user update Successfully");
                    return Redirect("/Responsible/Index");
                }
                else
                    TempData["Msg"] = alertHtml_error(respView.RESPONSABLE_APELLIDO, "user update error");
            }
            return View(respView);
        }

        public ActionResult DeleteResponsible(Int32 iRespId)
        {
            var responsible = responsibleService.GetResponsables().Find(smodel => smodel.RESPONSABLE_ID == iRespId);
            return PartialView("DeleteResponsible", responsible);
        }
        [HttpPost]
        public ActionResult DeleteResponsible(ResponsibleModel respView)
        {
            if (responsibleService.ValidateResponsible(respView))
            {
                if (responsibleService.SetStatusInactive(respView))
                    TempData["Msg"] = alertHtml_ok(respView.RESPONSABLE_APELLIDO, " eliminado correctamente");
                else
                    TempData["Msg"] = alertHtml_error(respView.RESPONSABLE_APELLIDO, " error");
            }
            else
            {
                TempData["Msg"] = alertHtml_error(respView.RESPONSABLE_APELLIDO, " tiene asignnado un infante y no se puede eliminar");
            }
            return Redirect("/Responsible/Index");
        }

        public void ExportListToCSV()
        {

            StringWriter sw = new StringWriter();

            sw.WriteLine("\"Id\",\"Nombre\",\"Apellido\",\"Documento\",\"Tipo documento\",\"Tipo nacionalidad\"");

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment;filename=CSV_Reponsables.csv");
            Response.ContentType = "text/csv";

            var responsibleList = responsibleService.GetResponsables();

            foreach (var line in responsibleList)
            {
                sw.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"",
                                           line.RESPONSABLE_ID,
                                           line.RESPONSABLE_NOMBRE,
                                           line.RESPONSABLE_APELLIDO,
                                           line.RESPONSABLE_DOCUMENTO,
                                           line.RESPONSABLE_TIPODOCUMENTO_ID,
                                           line.RESPONSABLE_TIPONACIONALIDAD_ID));
            }

            Response.Write(sw.ToString());

            Response.End();

        }
    }
}

cpi-bo/Views/Responsible/AddResponsible.cshtml
@model cpi_bo.Models.ResponsibleModel

@{
    ViewBag.Title = "AddResponsable";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Ingreso de responsable</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RESPONSABLE_NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RESPONSABLE_APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_DOCUMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RESPONSABLE_DOCUMENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_DOCUMENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID, new SelectList(ViewBag.comboDocumentType, "ID", "DESCRIPCION"), "Seleccionar Tipo Documento", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID, new SelectList(ViewBag.comboNationalityType, "ID", "DESCRIPCION"), "Seleccionar Tipo Nacionalidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>

cpi-bo/Views/Responsible/DeleteResponsible.cshtml
@model cpi_bo.Models.ResponsibleModel
@using (Html.BeginForm("DeleteResponsible", "Responsible"))
{
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Esta seguro que quiere eliminar al responsable @Model.RESPONSABLE_APELLIDO?</h4>
            </div>
            <div class="modal-body">
                <h2>@ViewBag.Msg</h2>
                @Html.HiddenFor(modelItem => Model.RESPONSABLE_ID)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success">Eliminar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

}

cpi-bo/Views/Responsible/EditResponsible.cshtml
@model cpi_bo.Models.ResponsibleModel

@{
    ViewBag.Title = "EditResponsable";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edición de responsable</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(model => model.RESPONSABLE_ID)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RESPONSABLE_NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RESPONSABLE_APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_DOCUMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RESPONSABLE_DOCUMENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_DOCUMENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID, new SelectList(ViewBag.comboDocumentType, "ID", "DESCRIPCION"), "Seleccionar Tipo Documento", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID, new SelectList(ViewBag.comboNationalityType, "ID", "DESCRIPCION"), "Seleccionar Tipo Nacionalidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>

cpi-bo/Views/Responsible/Index.cshtml
@model IEnumerable<cpi_bo.Models.ResponsibleModel>
@using cpi_bo.Helpers

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Lista de responsables</h2>

<div class="table-responsive">
    <table id="tblResponsables" class="table table-striped table-hover table-condensed" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RESPONSABLE_NOMBRE)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RESPONSABLE_APELLIDO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RESPONSABLE_DOCUMENTO)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RESPONSABLE_TIPODOCUMENTO_ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RESPONSABLE_TIPONACIONALIDAD_ID)
                </th>
                <th></th>
            </tr>
         </thead>
            @foreach (var item in Model)
            {
                @Html.HiddenFor(modelItem => item.RESPONSABLE_ID)
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RESPONSABLE_NOMBRE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RESPONSABLE_APELLIDO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RESPONSABLE_DOCUMENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RESPONSABLE_TIPODOCUMENTO_DESCRIPCION)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RESPONSABLE_TIPONACIONALIDAD_DESCRIPCION)
                    </td>
                    <td>
                        @SeguridadTagHelper.SegHrefBtnConIcono("/Responsible/EditResponsible?iRespId=" + item.RESPONSABLE_ID, "btn-sm btn-warning", "glyphicon-pencil", "Edit Responsible", "", "MOD_RESP")
                        &nbsp*
                        @SeguridadTagHelper.SegHrefAjaxConModalIcon("/Responsible/DeleteResponsible?iRespId=" + item.RESPONSABLE_ID, "btn-sm btn-danger hidden-print", "modalDeleteResponsible", "glyphicon-lock", "", "Delete Responsible", "DEL_RESP")
                    </td>
                </tr>
            }

        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                Exportar
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="#"></a>@Html.ActionLink("Excel", "DowloadExcel", new { nameTable = "Responsables" })</li>
                <li><a href="#"></a>@Html.ActionLink("Csv", "ExportListToCSV", new { nameTable = "Responsables" })</li>
            </ul>
        </div>

    </table>
    <p>
        @SeguridadTagHelper.SegHrefBtnConIcono("/Responsible/AddResponsible", "btn btn-primary", "glyphicon-plus", "Agregar Responsables", "Nuevo Responsable", "ADD_RESP")
    </p>
</div>
<div class="ExportSection">
    @Html.ActionLink("Export to Csv", "ExportEmployeesListToCSV")
    @Html.ActionLink("Exportar a Excel", "DowloadExcel", new { nameTable = "Responsables" }, new { @class = "btn-success glyphicon-download-alt" })
</div>

<div class="modal fade" id="modalDeleteResponsible" tabindex="-1" role="dialog">
</div>

<script>

        $(document).ready(function () {

            $('.detailsUser_icon').html("<i class='glyphicon glyphicon-list-alt ' aria-hidden='true' data-toggle='tooltip' title = 'Ver detalles' ></i>");
            $('#tblResponsables').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
            });
        });
</script>