cpi-bo/Controllers/KidController.cs
using cpi_bo.Helpers;
using cpi_bo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.UI;
using cpi_bo.Services;

namespace cpi_bo.Controllers
{
    public class KidController : AbstractSeguridadController
    {
        private TypeTableService typeTableService = new TypeTableService();
        KidService kidService = new KidService();
        SurveyService survey = new SurveyService();
        // GET: Kid
        public ActionResult Index()
        {
            return View(kidService.GetKids());
        }

        public ActionResult AddKid()
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            ViewBag.comboRoomType = typeTableService.GetTypes("SALAS", "SALA_ID");
            return View();
        }
        [HttpPost]
        public ActionResult AddKid(KidModel kidView)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            ViewBag.comboRoomType = typeTableService.GetTypes("SALAS", "SALA_ID");
            if (ModelState.IsValid)
            {
                if (kidService.AddKid(kidView))
                {
                    TempData["Msg"] = alertHtml_ok(kidView.INFANTE_NOMBRE.ToUpper(), " fue agregado exitosamente");
                    return Redirect("/Kid/Index");
                }
                else
                    TempData["Msg"] = alertHtml_error(kidView.INFANTE_NOMBRE.ToUpper(), "no fue agregado - error");
            }
            return View(kidView);
        }

        public ActionResult EditKid(int kidId)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            ViewBag.comboRoomType = typeTableService.GetTypes("SALAS", "SALA_ID");
            return View(kidService.GetKids().Find(smodel => smodel.INFANTE_ID == kidId));
        }
        [HttpPost]
        public ActionResult EditKid(KidModel kidView)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            ViewBag.comboRoomType = typeTableService.GetTypes("SALAS", "SALA_ID");
            if (ModelState.IsValid)
            {
                if (kidService.UpdateKid(kidView))
                {
                    TempData["Msg"] = alertHtml_ok(kidView.INFANTE_NOMBRE, " fue guardado exitosamente");
                    return Redirect("/Kid/Index");
                }
                else
                    TempData["Msg"] = alertHtml_error(kidView.INFANTE_NOMBRE, "no fue guardado - error");
            }
            return View(kidView);
        }

        public ActionResult DeleteKid(Int32 kidId)
        {
            var kid = kidService.GetKids().Find(smodel => smodel.INFANTE_ID == kidId);
            return PartialView("DeleteKid", kid);
        }
        [HttpPost]
        public ActionResult DeleteKid(KidModel kidView)
        {
            if (kidService.SetStatusInactive(kidView))
                TempData["Msg"] = alertHtml_ok(kidView.INFANTE_APELLIDO, " eliminado correctamente");
            else
                TempData["Msg"] = alertHtml_error(kidView.INFANTE_APELLIDO, " error");

            return Redirect("/Kid/Index");
        }

        public ActionResult SurveyKid(int id)
        {
            ViewBag.infanteId = id;
            return View();
        }
        
        public JsonResult IndexSurvey(int infanteId)
        {
            try { 
            var surveyKid = survey.GetFamilyOrganization().Find(smodel => smodel.IDINFANTE == infanteId);

            // se elimina los objetos que hacen recursividad 
            if(surveyKid == null)
            {
                var surveyFamilia = new FamilyOrganization();
                surveyFamilia.ID = 0;
                surveyFamilia.FAMILIARACARGO = 0;
                surveyFamilia.FAMILIARPRIVADOLIBERTAD = 0;
                surveyFamilia.CANTIDADHERMANOS = 0;
                surveyFamilia.MADREADOLECENTE = 0;
                surveyFamilia.FAMILIAREMBARAZADA = 0;
                surveyFamilia.IDINFANTE = infanteId;

                surveyKid = surveyFamilia;
            }

            return Json((surveyKid), JsonRequestBehavior.AllowGet);
            }
            catch(Exception e)
            {
                return null;
            }
        }

        public JsonResult IndexHealth(int infanteId)
        {
            try
            {
                var surveyKid = survey.GetHealth().Find(smodel => smodel.IDINFANTE == infanteId);

                // se elimina los objetos que hacen recursividad 
                if (surveyKid == null)
                {
                    var surveyHealth = new Health();
                    surveyHealth.ID = 0;
                    surveyHealth.CONDICIONESDESALUDFAMILIAR = 0;
                    surveyHealth.COBERTURADESALUDFAMILIAR = 0;
                    surveyHealth.CONTROLDESALUDDELINFANTE = 0;
                    surveyHealth.VACUNACIONDELINFANTE = 0;
                    surveyHealth.IDINFANTE = infanteId;

                    surveyKid = surveyHealth;
                }

                return Json((surveyKid), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public JsonResult IndexEducation(int infanteId)
        {
            try
            {
                var surveyKid = survey.GetEducation().Find(smodel => smodel.IDINFANTE == infanteId);

                // se elimina los objetos que hacen recursividad 
                if (surveyKid == null)
                {
                    var surveyEducation = new Education();
                    surveyEducation.ID = 0;
                    surveyEducation.ESCOLARIZACIONDELOSINFANTES = 0;
                    surveyEducation.MADREADOLESCENTE = 0;
                    surveyEducation.IDINFANTE = infanteId;

                    surveyKid = surveyEducation;
                }

                return Json((surveyKid), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public JsonResult IndexWorkSituation(int infanteId)
        {
            try
            {
                var surveyKid = survey.GetWorkSituation().Find(smodel => smodel.IDINFANTE == infanteId);

                // se elimina los objetos que hacen recursividad 
                if (surveyKid == null)
                {
                    var surveyWorkSituation = new WorkSituation();
                    surveyWorkSituation.ID = 0;
                    surveyWorkSituation.TRABAJOENLAFAMILIA = 0;
                    surveyWorkSituation.TRABAJOMENORDEEDAD = 0;
                    surveyWorkSituation.IDINFANTE = infanteId;

                    surveyKid = surveyWorkSituation;
                }

                return Json((surveyKid), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public JsonResult IndexFamilyEconomy(int infanteId)
        {
            try
            {
                var surveyKid = survey.GetFamilyEconomy().Find(smodel => smodel.IDINFANTE == infanteId);

                // se elimina los objetos que hacen recursividad 
                if (surveyKid == null)
                {
                    var surveyFamilyEconomy = new FamilyEconomy();
                    surveyFamilyEconomy.ID = 0;
                    surveyFamilyEconomy.UBICACIONINGRESOFAMILIAR = 0;
                    surveyFamilyEconomy.BENEFICIOSOCIAL = 0;
                    surveyFamilyEconomy.IDINFANTE = infanteId;

                    surveyKid = surveyFamilyEconomy;
                }

                return Json((surveyKid), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public JsonResult IndexDwelling(int infanteId)
        {
            try
            {
                var surveyKid = survey.GetDwelling().Find(smodel => smodel.IDINFANTE == infanteId);

                // se elimina los objetos que hacen recursividad 
                if (surveyKid == null)
                {
                    var surveyDwelling = new Dwelling();
                    surveyDwelling.ID = 0;
                    surveyDwelling.TIPOVIVIENDA = 0;
                    surveyDwelling.TIPOPROPIEDAD = 0;
                    surveyDwelling.CANTIDADPERSONASPORHABITACION = 0;
                    surveyDwelling.SERVICIOSVIVIENDA = 0;
                    surveyDwelling.IDINFANTE = infanteId;

                    surveyKid = surveyDwelling;
                }

                return Json((surveyKid), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public JsonResult IndexSocialProblem(int infanteId)
        {

cpi-bo/Views/Kid/AddKid.cshtml
    @model cpi_bo.Models.KidModel

@{
    ViewBag.Title = "AddKid";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Agregar infante</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_DOCUMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_DOCUMENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_DOCUMENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_TIPODOCUMENTO_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_TIPODOCUMENTO_ID, new SelectList(ViewBag.comboDocumentType, "ID", "DESCRIPCION"), "Seleccionar Tipo Documento", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_TIPODOCUMENTO_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            List<SelectListItem> listGender = new List<SelectListItem>();
            listGender.Add(new SelectListItem
            {
                Text = "Masculino",
                Value = "M"
            });
            listGender.Add(new SelectListItem
            {
                Text = "Femenino",
                Value = "F",
                Selected = true
            });
        }

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_GENERO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_GENERO, new SelectList(listGender, "Value", "Text"), "Seleccionar género", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_GENERO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_NACIONALIDAD_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_NACIONALIDAD_ID, new SelectList(ViewBag.comboNationalityType, "ID", "DESCRIPCION"), "Seleccionar Tipo Nacionalidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_NACIONALIDAD_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_FECHANACIMIENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_FECHANACIMIENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_FECHANACIMIENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_FECHAINGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_FECHAINGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_FECHAINGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_DOMICILIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_DOMICILIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_DOMICILIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_LOCALIDAD_CODIGOPOSTAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_LOCALIDAD_CODIGOPOSTAL, new SelectList(ViewBag.comboLocation, "ID", "DESCRIPCION"), "Seleccionar Localidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_LOCALIDAD_CODIGOPOSTAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_SALA_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_SALA_ID, new SelectList(ViewBag.comboRoomType, "ID", "DESCRIPCION"), "Seleccionar Sala", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_SALA_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_FECHAEGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_FECHAEGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_FECHAEGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>

cpi-bo/Views/Kid/DeleteKid.cshtml
@model cpi_bo.Models.KidModel
@using (Html.BeginForm("DeleteKid", "Kid"))
{
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Esta seguro que quiere eliminar al infante @Model.INFANTE_APELLIDO?</h4>
            </div>
            <div class="modal-body">
                <h2>@ViewBag.Msg</h2>
                @Html.HiddenFor(modelItem => Model.INFANTE_ID)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-success">Eliminar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

}

cpi-bo/Views/Kid/EditKid.cshtml
@model cpi_bo.Models.KidModel

@{
    ViewBag.Title = "EditKid";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edición de infantes</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.HiddenFor(model => model.INFANTE_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_DOCUMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_DOCUMENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_DOCUMENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_TIPODOCUMENTO_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_TIPODOCUMENTO_ID, new SelectList(ViewBag.comboDocumentType, "ID", "DESCRIPCION"), "Seleccionar Tipo Documento", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_TIPODOCUMENTO_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            List<SelectListItem> listGender = new List<SelectListItem>();
            listGender.Add(new SelectListItem
            {
                Text = "Masculino",
                Value = "M"
            });
            listGender.Add(new SelectListItem
            {
                Text = "Femenino",
                Value = "F",
                Selected = true
            });
        }

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_GENERO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_GENERO, new SelectList(listGender, "Value", "Text"), "Seleccionar género", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_GENERO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_NACIONALIDAD_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_NACIONALIDAD_ID, new SelectList(ViewBag.comboNationalityType, "ID", "DESCRIPCION"), "Seleccionar Tipo Nacionalidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_NACIONALIDAD_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_FECHANACIMIENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_FECHANACIMIENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_FECHANACIMIENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_FECHAINGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_FECHAINGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_FECHAINGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_DOMICILIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_DOMICILIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_DOMICILIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_LOCALIDAD_CODIGOPOSTAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_LOCALIDAD_CODIGOPOSTAL, new SelectList(ViewBag.comboLocation, "ID", "DESCRIPCION"), "Seleccionar Localidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_LOCALIDAD_CODIGOPOSTAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_SALA_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.INFANTE_SALA_ID, new SelectList(ViewBag.comboRoomType, "ID", "DESCRIPCION"), "Seleccionar Sala", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.INFANTE_SALA_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.INFANTE_FECHAEGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.INFANTE_FECHAEGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.INFANTE_FECHAEGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>