cpi-bo/Controllers/EmployeesController.cs
using cpi_bo.Helpers;
using cpi_bo.Models;
using System;
using System.IO;
using System.Web.UI;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using cpi_bo.Services;

namespace cpi_bo.Controllers
{
    public class EmployeesController : AbstractSeguridadController
    {
        private TypeTableService typeTableService = new TypeTableService();
        private EmployeesService employeesService = new EmployeesService();
        // GET: Employees
        public ActionResult Index()
        {
            ModelState.Clear();
            if (TempData["Msg"] != null)
                ViewBag.Message = TempData["Msg"].ToString();

            return View(employeesService.GetEmployees());
        }

        public ActionResult AddEmployees()
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboMaritalStatus = typeTableService.GetTypes("ESTADOSCIVILES", "ESTADOCIVIL_ID");
            ViewBag.comboSocialWork = typeTableService.GetTypes("OBRASOCIAL", "OBRASOCIAL_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            return View();
        }
        [HttpPost]
        public ActionResult AddEmployees(EmployeesModel EmployeesView)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboMaritalStatus = typeTableService.GetTypes("ESTADOSCIVILES", "ESTADOCIVIL_ID");
            ViewBag.comboSocialWork = typeTableService.GetTypes("OBRASOCIAL", "OBRASOCIAL_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            if (ModelState.IsValid)
            {
                if (employeesService.AddEmployees(EmployeesView))
                {
                    TempData["Msg"] = alertHtml_ok(EmployeesView.EMPLEADO_NOMBRE.ToUpper(), "Empleado agregado con éxito");
                    return Redirect("/Employees/Index");
                }
                else
                    TempData["Msg"] = alertHtml_error(EmployeesView.EMPLEADO_NOMBRE.ToUpper(), "Error al agregar empleado");                
            }
            return View(EmployeesView);
        }

        public ActionResult EditEmployees(string sEmployeesId)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboMaritalStatus = typeTableService.GetTypes("ESTADOSCIVILES", "ESTADOCIVIL_ID");
            ViewBag.comboSocialWork = typeTableService.GetTypes("OBRASOCIAL", "OBRASOCIAL_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            var a = employeesService.GetEmployees().Find(x => x.EMPLEADO_ID == Convert.ToInt16(sEmployeesId));
            return View(a);
        }

        [HttpPost]
        public ActionResult EditEmployees(EmployeesModel EmployeesView)
        {
            ViewBag.comboDocumentType = typeTableService.GetTypes("TIPODOCUMENTOS", "TIPODOCUMENTO_ID");
            ViewBag.comboMaritalStatus = typeTableService.GetTypes("ESTADOSCIVILES", "ESTADOCIVIL_ID");
            ViewBag.comboSocialWork = typeTableService.GetTypes("OBRASOCIAL", "OBRASOCIAL_ID");
            ViewBag.comboNationalityType = typeTableService.GetTypes("TIPONACIONALIDADES", "TIPONACIONALIDAD_ID");
            ViewBag.comboLocation = typeTableService.GetTypes("LOCALIDADES", "LOCALIDAD_CODIGOPOSTAL");
            if (ModelState.IsValid)
            {
                if (employeesService.UpdateEmployees(EmployeesView))
                {
                    TempData["Msg"] = alertHtml_ok(EmployeesView.EMPLEADO_NOMBRE.ToUpper(), " actualización de empleado con éxito");
                    return Redirect("/Employees/Index");
                }
                else
                    TempData["Msg"] = alertHtml_error(EmployeesView.EMPLEADO_NOMBRE.ToUpper(), " error de actualización del empleado");
            }
            return View(EmployeesView);
        }

        public ActionResult DeleteEmployees(Int32 iEmpId)
        {
            var employees = employeesService.GetEmployees().Find(smodel => smodel.EMPLEADO_ID == iEmpId);
            return PartialView("DeleteEmployees", employees);
        }
        [HttpPost]
        public ActionResult DeleteEmployees(EmployeesModel EmployeesView)
        {
            if (employeesService.ValidateEmployees(EmployeesView))
            {
                if (employeesService.SetStatusInactive(EmployeesView))
                    TempData["Msg"] = alertHtml_ok(EmployeesView.EMPLEADO_APELLIDO, " eliminado correctamente");
                else
                    TempData["Msg"] = alertHtml_ok(EmployeesView.EMPLEADO_APELLIDO, " eliminado correctamente");
            }
            else
            {
                TempData["Msg"] = alertHtml_error(EmployeesView.EMPLEADO_APELLIDO, " tiene asignado un familiar y no se puede eliminar");
            }
            return Redirect("/Employees/Index");
        }

        public JsonResult VerifyDoc(string sDocEmployees)
        {
            bool result;
            string message = "";
            if (employeesService.ExistEmployeesDNI(sDocEmployees))
            {
                message = alertHtml_ok(sDocEmployees, "El documento es valido");
                result = true;
            }
            else
            {
                message = alertHtml_error(sDocEmployees, "El documento ya existe");
                result = false;
            }
            return Json(new { result = result, message = message }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult VerifyCuil(string sCuilEmployees)
        {
            bool result;
            string message = "";
            if (employeesService.ExistEmployeesCUIL(sCuilEmployees))
            {
                message = alertHtml_ok(sCuilEmployees, "El cuil es valido");
                result = true;
            }
            else
            {
                message = alertHtml_error(sCuilEmployees, "El cuil ya existe");
                result = false;
            }
            return Json(new { result = result, message = message }, JsonRequestBehavior.AllowGet);
        }

        public void ExportListToCSV()
        {

            StringWriter sw = new StringWriter();

            sw.WriteLine("\"Nombre\",\"Apellido\",\"Fecha de Nacimiento\",\"Estado Civil\",\"Cantidad de hijos\",\"Domicilio\",\"Email\",\"Localidad\",\"Documento\",\"CUIL\",\"Nacionalidad\",\"Fecha de Ingreso\",\"Estado\",\"Tipo de documento\",\"Número de afiliado\",\"Obra Social\"");

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment;filename=CSV_Empleados.csv");
            Response.ContentType = "text/csv";

            var employeesList = employeesService.GetEmployees();

            foreach (var line in employeesList)
            {
                sw.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\",\"{8}\",\"{9}\",\"{10}\",\"{11}\",\"{12}\",\"{13}\",\"{14}\",\"{15}\"",
                                           line.EMPLEADO_NOMBRE,
                                           line.EMPLEADO_APELLIDO,
                                           line.EMPLEADO_FECHANACIMIENTO,
                                           line.EMPLEADO_ESTADOCIVIL,
                                           line.EMPLEADO_CANTIDADHIJOS,
                                           line.EMPLEADO_DOMICILIO,
                                           line.EMPLEADO_EMAIL,
                                           line.EMPLEADO_LOCALIDAD_CODIGOPOSTAL,
                                           line.EMPLEADO_DOCUMENTO,
                                           line.EMPLEADO_CUIL,
                                           line.EMPLEADO_NACIONALIDAD_ID,
                                           line.EMPLEADO_FECHAINGRESO,
                                           line.EMPLEADO_ESTADO_ID,
                                           line.EMPLEADO_TIPODOCUMENTO_ID,
                                           line.EMPLEADO_NUMEROAFILIADO,
                                           line.EMPLEADO_OBRASOCIAL_ID));
            }

            Response.Write(sw.ToString());

            Response.End();

        }
    }
}

cpi-bo/Views/Employees/AddEmployees.cshtml
@model cpi_bo.Models.EmployeesModel

@{
    ViewBag.Title = "AddEmployees";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Agregar empleados</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_NOMBRE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_NOMBRE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_APELLIDO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_APELLIDO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_APELLIDO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_NACIONALIDAD_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EMPLEADO_NACIONALIDAD_ID, new SelectList(ViewBag.comboNationalityType, "ID", "DESCRIPCION"), "Seleccionar Nacionalidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMPLEADO_NACIONALIDAD_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_TIPODOCUMENTO_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EMPLEADO_TIPODOCUMENTO_ID, new SelectList(ViewBag.comboDocumentType, "ID", "DESCRIPCION"), "Seleccionar tipo de documento", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMPLEADO_TIPODOCUMENTO_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_DOCUMENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_DOCUMENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_DOCUMENTO, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="docverify">

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_CUIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_CUIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_CUIL, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="cuilverify">

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_FECHANACIMIENTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_FECHANACIMIENTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_FECHANACIMIENTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_ESTADOCIVIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EMPLEADO_ESTADOCIVIL, new SelectList(ViewBag.comboMaritalStatus, "ID", "DESCRIPCION"), "Seleccionar estado civil", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMPLEADO_ESTADOCIVIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_CANTIDADHIJOS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_CANTIDADHIJOS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_CANTIDADHIJOS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_DOMICILIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_DOMICILIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_DOMICILIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_LOCALIDAD_CODIGOPOSTAL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EMPLEADO_LOCALIDAD_CODIGOPOSTAL, new SelectList(ViewBag.comboLocation, "ID", "DESCRIPCION"), "Seleccionar Localidad", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMPLEADO_LOCALIDAD_CODIGOPOSTAL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_FECHAINGRESO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_FECHAINGRESO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_FECHAINGRESO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_OBRASOCIAL_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EMPLEADO_OBRASOCIAL_ID, new SelectList(ViewBag.comboSocialWork, "ID", "DESCRIPCION"), "Seleccionar Obra Social", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EMPLEADO_OBRASOCIAL_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMPLEADO_NUMEROAFILIADO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMPLEADO_NUMEROAFILIADO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMPLEADO_NUMEROAFILIADO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al menú", "Index")
</div>

<script>

    $("#EMPLEADO_DOCUMENTO").focusout(function () {
        employeesVerify($("#EMPLEADO_DOCUMENTO").val());
    });


    function employeesVerify(sDocEmployees) {
        $.ajax(
        {
            type: 'GET',
            data: { sDocEmployees: sDocEmployees },
            contentType: "application/json; charset=utf-8",
            dataType: 'json',
            async: true,
            url: '/Employees/VerifyDoc/',
            success: function (result) {
                $("#docverify").empty();
                if (result.result) {
                    $("#docverify").append(result.message);
                } else {
                    $("#docverify").append(result.message);
                }
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    };

</script>
<script>

    $("#EMPLEADO_CUIL").focusout(function () {
        employeesVerifyCUIL($("#EMPLEADO_CUIL").val());
    });


    function employeesVerifyCUIL(sCuilEmployees) {
        $.ajax(
        {
            type: 'GET',
            data: { sCuilEmployees: sCuilEmployees },
            contentType: "application/json; charset=utf-8",
            dataType: 'json',
            async: true,
            url: '/Employees/VerifyCuil/',
            success: function (result) {
                $("#cuilverify").empty();
                if (result.result) {
                    $("#cuilverify").append(result.message);
                } else {
                    $("#cuilverify").append(result.message);
                }
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    };

</script>

cpi-bo/Views/Employees/DeleteEmployees.cshtml
@model cpi_bo.Models.EmployeesModel
@using (Html.BeginForm("DeleteEmployees", "Employees"))
{
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Esta seguro que quiere eliminar al empleado @Model.EMPLEADO_APELLIDO?</h4>
            </div>
            <div class="modal-body">
                <h2>@ViewBag.Msg</h2>
                @Html.HiddenFor(modelItem => Model.EMPLEADO_ID)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-success">Eliminar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

}

cpi-bo/Views/Employees/Index.cshtml
@model IEnumerable<cpi_bo.Models.EmployeesModel>
@using cpi_bo.Helpers

@{
    ViewBag.Title = "Empleados";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Listado de empleados</h2>

<div class="table-responsive">
    @if (ViewBag.Message != null)
    {
        @Html.Raw(ViewBag.Message)
    }

    <div class="row">
        <div class="col-sm-2">
            <p>
                @SeguridadTagHelper.SegHrefBtnConIcono("/Employees/AddEmployees", "btn btn-primary", "glyphicon-plus", "Agregar empleado", "Nuevo Empleado", "ADD_EMP")
            </p>
        </div>

        <div class="col-sm-6">
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    Exportar
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="#"></a>@Html.ActionLink("Excel", "DowloadExcel", new { nameTable = "Empleados" })</li>
                    <li><a href="#"></a>@Html.ActionLink("Csv", "ExportListToCSV", new { nameTable = "Empleados" })</li>
                </ul>
            </div>
        </div>
     </div>


        <table id="tblEmployees" class="table table-striped table-hover table-condensed" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_NOMBRE)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_APELLIDO)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_FECHANACIMIENTO)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_DOMICILIO)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_LOCALIDAD_CODIGOPOSTAL)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_DOCUMENTO)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_CUIL)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_NACIONALIDAD_ID)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EMPLEADO_FECHAINGRESO)
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_NOMBRE)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_APELLIDO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_FECHANACIMIENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_DOMICILIO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_LOCALIDAD_CODIGOPOSTAL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_DOCUMENTO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_CUIL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_DESCRIPCION)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMPLEADO_FECHAINGRESO)
                    </td>
                    <td>
                        @SeguridadTagHelper.SegHrefBtnConIcono("/Employees/EditEmployees?sEmployeesId=" + item.EMPLEADO_ID, "btn-sm btn-warning", "glyphicon-pencil", "Editar empleado", "", "MOD_EMP")
                    </td>
                    <td>
                        @SeguridadTagHelper.SegHrefAjaxConModalIcon("/Employees/DeleteEmployees?iEmpId=" + item.EMPLEADO_ID, "btn-sm btn-danger hidden-print", "modalDeleteEmployees", "glyphicon-lock", "", "Eliminar empleado", "DEL_EMP")
                    </td>
                </tr>
            }      
</table>

    </div>
<div class="modal fade " id="modalAddEmployees" tabindex="-1" role="dialog">
</div>
<div class="modal fade " id="modalEditEmployees" tabindex="-1" role="dialog">
</div>
<div class="modal fade" id="modalDetailEmployees" tabindex="-1" role="dialog">
</div>
<div class="modal fade" id="modalDeleteEmployees" tabindex="-1" role="dialog">
</div>
<div class="modal fade" id="modalViewPerm" tabindex="-1" role="dialog">
</div>

<script>
        $(document).ready(function () {
            $('.detailsEmployees_icon').html("<i class='glyphicon glyphicon-list-alt ' aria-hidden='true' data-toggle='tooltip' title = 'Ver detalles' ></i>");
            $('#tblEmployees').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                }
            });
        });
</script>